title: Site

tabs: 
  main:
    sections:
      primary:
        type: pages
        label: Pages
        template:
          - about
          - apply
          - calendar
          - events
          - traces
          - home
  events:
    sections:
      events:
        type: pages
        parent: site.find('events')
  traces:
    sections:
      traces:
        type: pages
        parent: site.find('traces')
