title: Site

tabs: 
  main:
    sections:
      primary:
        type: pages
        label: Pages
        template:
          - home
          - about
          - apply
          - calendar
          - events
          - traces
        status: published
        sortBy: status desc date desc
      forms: 
        type: pages
        parent: site.find('forms')
        template: form
        # forms: dreamform/pages/forms



        
  events:
    sections:
      events:
        type: pages
        parent: site.find('events')
  traces:
    sections:
      traces:
        type: pages
        parent: site.find('traces')
